# Tratando dados faltantes

## Train

In [52]:
import pandas as pd

In [53]:
df_train = pd.read_csv('train.csv').drop(columns='Unnamed: 0')
df_train.head()

,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,CO_MUNICIPIO_NASCIMENTO,NO_MUNICIPIO_NASCIMENTO,CO_UF_NASCIMENTO,SG_UF_NASCIMENTO,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_ESCOLA,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,IN_BAIXA_VISAO,IN_CEGUEIRA,IN_SURDEZ,IN_DEFICIENCIA_AUDITIVA,IN_SURDO_CEGUEIRA,IN_DEFICIENCIA_FISICA,IN_DEFICIENCIA_MENTAL,IN_DEFICIT_ATENCAO,IN_DISLEXIA,IN_DISCALCULIA,IN_AUTISMO,IN_VISAO_MONOCULAR,IN_OUTRA_DEF,IN_SABATISTA,IN_GESTANTE,IN_LACTANTE,IN_IDOSO,IN_ESTUDA_CLASSE_HOSPITALAR,IN_SEM_RECURSO,IN_BRAILLE,IN_AMPLIADA_24,IN_AMPLIADA_18,IN_LEDOR,IN_ACESSO,IN_TRANSCRICAO,IN_LIBRAS,IN_LEITURA_LABIAL,IN_MESA_CADEIRA_RODAS,IN_MESA_CADEIRA_SEPARADA,IN_APOIO_PERNA,IN_GUIA_INTERPRETE,IN_MACA,IN_COMPUTADOR,IN_CADEIRA_ESPECIAL,IN_CADEIRA_CANHOTO,IN_CADEIRA_ACOLCHOADA,IN_PROVA_DEITADO,IN_MOBILIARIO_OBESO,IN_LAMINA_OVERLAY,IN_PROTETOR_AURICULAR,IN_MEDIDOR_GLICOSE,IN_MAQUINA_BRAILE,IN_SOROBAN,IN_MARCA_PASSO,IN_SONDA,IN_MEDICAMENTOS,IN_SALA_INDIVIDUAL,IN_SALA_ESPECIAL,IN_SALA_ACOMPANHANTE,IN_MOBILIARIO_ESPECIFICO,IN_MATERIAL_ESPECIFICO,IN_NOME_SOCIAL,IN_CERTIFICADO,NO_ENTIDADE_CERTIFICACAO,CO_UF_ENTIDADE_CERTIFICACAO,SG_UF_ENTIDADE_CERTIFICACAO,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,CO_PROVA_CN,CO_PROVA_CH,CO_PROVA_LC,CO_PROVA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TX_RESPOSTAS_CN,TX_RESPOSTAS_CH,TX_RESPOSTAS_LC,TX_RESPOSTAS_MT,TP_LINGUA,TX_GABARITO_CN,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025,Q026,Q027,Q028,Q029,Q030,Q031,Q032,Q033,Q034,Q035,Q036,Q037,Q038,Q039,Q040,Q041,Q042,Q043,Q044,Q045,Q046,Q047,Q048,Q049,Q050
0,ed50e8aaa58e7a806c337585efee9ca41f1eb1ad,2016,4314902,Porto Alegre,43,RS,24,M,0.0,1,1,4314902.0,Porto Alegre,43.0,RS,1,4,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,4314902,Porto Alegre,43,RS,1,1,1,1,16f84b7b3d2aeaff7d2f01297e6b3d0e25c77bb2,9cd70f1b922e02bd33453b3f607f5a644fb9b1b8,01af53cd161a420fff1767129c10de560cc264dd,97caab1e1533dba217deb7ef41490f52e459ab01,436.3,495.4,581.2,399.4,ABACCABDBEDEDEEDDDBBBDAABABECDCCCAAABCBEEABCA,BBEBCAEBCEDBDDEBCACDBCBDABDDCDBEDCEAEABCAADAC,99999DCABCABCBBCADBCBBABAEADBEEBEDAAABAEAECCBB...,AECCCBABDCADDBCBCCADADBBAADEBCEEBABCDDEAABCAA,1,BCADBCEDCCBADBDCADBEBDBEADCCAEACDBEDBCACAEBEE,BCBCCADCCBEDDBEEADBDCECCBBECAEEDDADCDDACAADBA,CEDEACCBEBDBABECABDADEADCEDCBEBBCEBAAEBAAECBBC...,DADCCECBDECADCBACDBCEEABDDAABDBCEADDBECEBAEBC,1.0,120.0,120.0,120.0,80.0,80.0,520.0,D,D,B,B,3,C,A,B,B,B,A,B,A,A,A,A,A,A,B,A,A,C,A,A,A,C,H,E,5.0,5.0,1.0,0.0,0.0,5,5,0,5,5,5,5,5.0,A,A,A,A,A,A,A,B,D
1,2c3acac4b33ec2b195d77e7c04a2d75727fad723,2016,2304707,Granja,23,CE,17,F,0.0,3,1,2304707.0,Granja,23.0,CE,2,0,2,1.0,0,23005157.0,2304707.0,Granja,23.0,CE,2.0,1.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,2304707,Granja,23,CE,1,1,1,1,b9b06ce8c319a3df2158ea3d0aef0f7d3eecaed7,909237ab0d84688e10c0470e2997348aff585273,01af53cd161a420fff1767129c10de560cc264dd,97caab1e1533dba217deb7ef41490f52e459ab01,474.5,544.1,599.0,459.8,EDAAABDABADBCCAEDCDDECABADBEECBBAEEDCABCAABBC,ADCAABAADCEDAACDACEEDACBDCBACEDEDBACAADADABDC,99999ACBACDBDBCEADDAEEADCCEACEEDBECAAAACBECDAC...,AEDACBDECEDAEEAEDDEBDECDCECACADCACACAABDACEAB,1,EBEECADBCABECDDBEADCCABDEABEBCADBADDCCCEDBBCA,DCECBAAADCBBECAEDCEDDACCBDDACEDDBADBCADBCBCEE,CEDEACCBEBDBABECABDADEADCEDCBEBBCEBAAEBAAECBBC...,DADCCECBDECADCBACDBCEEABDDAABDBCEADDBECEBAEBC,1.0,140.0,120.0,120.0,120.0,80.0,580.0,A,A,A,A,5,B,A,B,B,A,A,B,A,A,A,A,A,A,B,A,A,A,A,A,A,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5,1,1,1,1,1,NaN,A,A,C,A,B,A,A,C,A
2,f4545f8ccb9ff5c8aad7d32951b3f251a26e6568,2016,2304400,Fortaleza,23,CE,21,F,0.0,3,1,2304400.0,Fortaleza,23.0,CE,3,0,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,2304400,Fortaleza,23,CE,0,0,0,0,2d22ac1d42e6187f09ee6c578df187a760123ccf,2d22ac1d42e6187f09ee6c578df187a760123ccf,2d22ac1d42e6187f09ee6c578df187a760123ccf,2d22ac1d42e6187f09ee6c578df187a760123ccf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,D,B,B,4,C,A,B,C,A,A,B,A,A,A,A,A,A,B,A,A,B,A,A,A,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5,5,5,5,5,5,NaN,A,A,A,A,C,A,A,B,A
3,3d6ec248fef899c414e77f82d5c6d2bffbeaf7fe,2016,3304557,Rio de Janeiro,33,RJ,25,F,0.0,0,1,3304557.0,Rio de Janeiro,33.0,RJ,1,9,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,3304557,Rio de Janeiro,33,RJ,0,0,0,0,2d22ac1d42e6187f09ee6c578df187a760123ccf,2d22ac1d42e6187f09ee6c578df187a760123ccf,2d22ac1d42e6187f09ee6c578df187a760123ccf,2d22ac1d42e6187f09ee6c578df187a760123ccf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,H,E,D,B,4,E,A,C,C,C,A,B,B,B,A,B,A,B,C,A,B,D,B,C,B,C,F,C,2.0,0.0,5.0,5.0,5.0,5,5,5,5,2,5,5,5.0,C,A,A,A,A,D,A,A,A
4,bf896ac8d3ecadd6dba1dfbf50110afcbf5d3268,2016,1302603,Manaus,13,AM,28,M,0.0,2,1,1505304.0,Oriximiná,15.0,PA,1,4,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1302603,Manaus,13,AM,0,0,0,0,2d22ac1d42e6187f09ee6c578df187a760123ccf,2d22ac1d42e6187f09ee6c578df187a760123ccf,2d22ac1d42e6187f09ee6c578df187a760123ccf,2d22ac1d42e6187f09ee6c578df187a760123ccf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,D,C,C,4,C,A,B,C,A,A,B,A,B,A,A,A,A,B,A,A,B,A,A,A,B,F,D,5.0,4.0,3.0,5.0,4.0,5,5,4,3,1,4,5,NaN,A,A,A,A,A,A,A,A,A

In [54]:
df_test = pd.read_csv('test.csv')
df_test.head()

,NU_INSCRICAO,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,TP_DEPENDENCIA_ADM_ESC,IN_BAIXA_VISAO,IN_CEGUEIRA,IN_SURDEZ,IN_DISLEXIA,IN_DISCALCULIA,IN_SABATISTA,IN_GESTANTE,IN_IDOSO,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q006,Q024,Q025,Q026,Q027,Q047
0,ba0cc30ba34e7a46764c09dfc38ed83d15828897,43,RS,19,F,1,1,1,3,1,NaN,NaN,0,0,0,0,0,0,0,0,1,1,0,0,495.3,593.3,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,E,H,B,B,C,D,A
1,177f281c68fa032aedbd842a745da68490926cd2,15,PA,24,M,3,2,1,4,1,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,C,B,A,A,C,D,A
2,6cf0d8b97597d7625cdedc7bdb6c0f052286c334,29,BA,16,F,2,1,3,0,1,NaN,NaN,0,0,0,0,0,0,0,0,1,1,0,0,559.1,529.3,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,F,G,B,B,A,NaN,D
3,5c356d810fa57671402502cd0933e5601a2ebf1e,41,PR,17,F,1,1,2,0,2,1.0,2.0,0,0,0,0,0,0,0,0,1,1,1,1,475.0,557.8,542.0,1,1.0,120.0,120.0,80.0,120.0,40.0,480.0,E,E,E,C,B,B,C,A
4,df47c07bd881c2db3f38c6048bf77c132ad0ceb3,53,DF,19,F,1,1,1,1,1,NaN,NaN,0,0,0,0,0,0,0,0,1,1,1,1,440.5,596.1,594.2,1,1.0,160.0,160.0,160.0,160.0,80.0,720.0,E,E,E,B,B,B,D,A

In [55]:
columns_intersection = list(set(df_train.columns).intersection(set(df_test.columns)))
columns_intersection.append('IN_TREINEIRO')
columns_intersection.remove('NU_INSCRICAO')

In [56]:
df_train_a = df_train[columns_intersection].copy()

In [57]:
df_train_a.head()

,IN_SABATISTA,NU_NOTA_COMP3,Q002,TP_STATUS_REDACAO,NU_IDADE,TP_NACIONALIDADE,NU_NOTA_LC,Q006,Q024,NU_NOTA_COMP2,TP_ENSINO,Q001,TP_SEXO,TP_LINGUA,TP_ESCOLA,Q047,IN_CEGUEIRA,NU_NOTA_CN,TP_COR_RACA,Q025,NU_NOTA_COMP4,IN_IDOSO,TP_PRESENCA_LC,TP_ST_CONCLUSAO,NU_NOTA_REDACAO,TP_PRESENCA_MT,NU_NOTA_CH,Q027,IN_BAIXA_VISAO,IN_DISCALCULIA,CO_UF_RESIDENCIA,NU_NOTA_COMP1,IN_SURDEZ,SG_UF_RESIDENCIA,TP_DEPENDENCIA_ADM_ESC,IN_DISLEXIA,TP_PRESENCA_CN,TP_PRESENCA_CH,NU_NOTA_COMP5,Q026,TP_ANO_CONCLUIU,IN_GESTANTE,IN_TREINEIRO
0,0,120.0,D,1.0,24,1,581.2,C,A,120.0,NaN,D,M,1,1,A,0,436.3,1,A,80.0,0,1,1,520.0,1,495.4,H,0,0,43,120.0,0,RS,NaN,0,1,1,80.0,C,4,0,0
1,0,120.0,A,1.0,17,1,599.0,B,A,120.0,1.0,A,F,1,2,A,0,474.5,3,A,120.0,0,1,2,580.0,1,544.1,NaN,0,0,23,140.0,0,CE,2.0,0,1,1,80.0,A,0,0,0
2,0,NaN,D,NaN,21,1,NaN,C,A,NaN,NaN,D,F,1,1,A,0,NaN,3,A,NaN,0,0,3,NaN,0,NaN,NaN,0,0,23,NaN,0,CE,NaN,0,0,0,NaN,A,0,0,0
3,0,NaN,E,NaN,25,1,NaN,E,C,NaN,NaN,H,F,0,1,D,0,NaN,0,B,NaN,0,0,1,NaN,0,NaN,F,0,0,33,NaN,0,RJ,NaN,0,0,0,NaN,C,9,0,0
4,0,NaN,D,NaN,28,1,NaN,C,A,NaN,NaN,E,M,1,1,A,0,NaN,2,A,NaN,0,0,1,NaN,0,NaN,F,0,0,13,NaN,0,AM,NaN,0,0,0,NaN,B,4,0,0

In [58]:
columns_selected = list(columns_intersection)

In [59]:
dados_faltantes = [{'Column':c,
                   'Per. Faltante':round(df_train_a[c].isna().sum() / df_train_a.shape[0], 3),
                   'dtype':df_train_a[c].dtype}
                   for c in df_train_a.columns if df_train_a[c].isna().sum() > 0]

In [60]:
pd.DataFrame(dados_faltantes).sort_values('Per. Faltante', ascending=False)

                    Column  Per. Faltante    dtype
4                TP_ENSINO          0.688  float64
11  TP_DEPENDENCIA_ADM_ESC          0.688  float64
9                     Q027          0.537   object
0            NU_NOTA_COMP3          0.262  float64
1        TP_STATUS_REDACAO          0.262  float64
2               NU_NOTA_LC          0.262  float64
3            NU_NOTA_COMP2          0.262  float64
6            NU_NOTA_COMP4          0.262  float64
7          NU_NOTA_REDACAO          0.262  float64
10           NU_NOTA_COMP1          0.262  float64
12           NU_NOTA_COMP5          0.262  float64
5               NU_NOTA_CN          0.247  float64
8               NU_NOTA_CH          0.247  float64

In [61]:
for c in ['TP_ENSINO', 'TP_DEPENDENCIA_ADM_ESC', 'Q027', 'CO_UF_RESIDENCIA']:
    columns_selected.remove(c)

In [62]:
columns_to_zero = ['NU_NOTA_COMP1', 
                   'NU_NOTA_COMP2', 
                   'NU_NOTA_COMP5', 
                   'NU_NOTA_LC', 
                   'TP_STATUS_REDACAO', 
                   'NU_NOTA_REDACAO', 
                   'NU_NOTA_COMP3', 
                   'NU_NOTA_COMP4',
                   'NU_NOTA_CN',
                   'NU_NOTA_CH']

In [63]:
df_train_a[columns_to_zero] = df_train_a[columns_to_zero].fillna(0)

In [64]:
df_train_a[columns_selected].head()

,IN_SABATISTA,NU_NOTA_COMP3,Q002,TP_STATUS_REDACAO,NU_IDADE,TP_NACIONALIDADE,NU_NOTA_LC,Q006,Q024,NU_NOTA_COMP2,Q001,TP_SEXO,TP_LINGUA,TP_ESCOLA,Q047,IN_CEGUEIRA,NU_NOTA_CN,TP_COR_RACA,Q025,NU_NOTA_COMP4,IN_IDOSO,TP_PRESENCA_LC,TP_ST_CONCLUSAO,NU_NOTA_REDACAO,TP_PRESENCA_MT,NU_NOTA_CH,IN_BAIXA_VISAO,IN_DISCALCULIA,NU_NOTA_COMP1,IN_SURDEZ,SG_UF_RESIDENCIA,IN_DISLEXIA,TP_PRESENCA_CN,TP_PRESENCA_CH,NU_NOTA_COMP5,Q026,TP_ANO_CONCLUIU,IN_GESTANTE,IN_TREINEIRO
0,0,120.0,D,1.0,24,1,581.2,C,A,120.0,D,M,1,1,A,0,436.3,1,A,80.0,0,1,1,520.0,1,495.4,0,0,120.0,0,RS,0,1,1,80.0,C,4,0,0
1,0,120.0,A,1.0,17,1,599.0,B,A,120.0,A,F,1,2,A,0,474.5,3,A,120.0,0,1,2,580.0,1,544.1,0,0,140.0,0,CE,0,1,1,80.0,A,0,0,0
2,0,0.0,D,0.0,21,1,0.0,C,A,0.0,D,F,1,1,A,0,0.0,3,A,0.0,0,0,3,0.0,0,0.0,0,0,0.0,0,CE,0,0,0,0.0,A,0,0,0
3,0,0.0,E,0.0,25,1,0.0,E,C,0.0,H,F,0,1,D,0,0.0,0,B,0.0,0,0,1,0.0,0,0.0,0,0,0.0,0,RJ,0,0,0,0.0,C,9,0,0
4,0,0.0,D,0.0,28,1,0.0,C,A,0.0,E,M,1,1,A,0,0.0,2,A,0.0,0,0,1,0.0,0,0.0,0,0,0.0,0,AM,0,0,0,0.0,B,4,0,0

In [65]:
df_train_a[columns_selected].to_csv('data/processed/train.csv',index=False)

## Test

In [66]:
columns_intersection.remove('IN_TREINEIRO')
columns_intersection.append('NU_INSCRICAO')

In [67]:
df_test_a = df_test[columns_intersection].copy()

In [68]:
df_test_a[columns_to_zero] = df_test_a[columns_to_zero].fillna(0)

In [69]:
columns_selected.remove('IN_TREINEIRO')
columns_selected.append('NU_INSCRICAO')

In [70]:
df_test_a[columns_selected].to_csv('data/processed/test.csv',index=False)

In [71]:
#

In [72]:
import numpy as np
import pandas as pd

In [73]:
pd.set_option('display.max_columns', None)

In [74]:
df_train = pd.read_csv('data/processed/train.csv')
df_train.head()

,IN_SABATISTA,NU_NOTA_COMP3,Q002,TP_STATUS_REDACAO,NU_IDADE,TP_NACIONALIDADE,NU_NOTA_LC,Q006,Q024,NU_NOTA_COMP2,Q001,TP_SEXO,TP_LINGUA,TP_ESCOLA,Q047,IN_CEGUEIRA,NU_NOTA_CN,TP_COR_RACA,Q025,NU_NOTA_COMP4,IN_IDOSO,TP_PRESENCA_LC,TP_ST_CONCLUSAO,NU_NOTA_REDACAO,TP_PRESENCA_MT,NU_NOTA_CH,IN_BAIXA_VISAO,IN_DISCALCULIA,NU_NOTA_COMP1,IN_SURDEZ,SG_UF_RESIDENCIA,IN_DISLEXIA,TP_PRESENCA_CN,TP_PRESENCA_CH,NU_NOTA_COMP5,Q026,TP_ANO_CONCLUIU,IN_GESTANTE,IN_TREINEIRO
0,0,120.0,D,1.0,24,1,581.2,C,A,120.0,D,M,1,1,A,0,436.3,1,A,80.0,0,1,1,520.0,1,495.4,0,0,120.0,0,RS,0,1,1,80.0,C,4,0,0
1,0,120.0,A,1.0,17,1,599.0,B,A,120.0,A,F,1,2,A,0,474.5,3,A,120.0,0,1,2,580.0,1,544.1,0,0,140.0,0,CE,0,1,1,80.0,A,0,0,0
2,0,0.0,D,0.0,21,1,0.0,C,A,0.0,D,F,1,1,A,0,0.0,3,A,0.0,0,0,3,0.0,0,0.0,0,0,0.0,0,CE,0,0,0,0.0,A,0,0,0
3,0,0.0,E,0.0,25,1,0.0,E,C,0.0,H,F,0,1,D,0,0.0,0,B,0.0,0,0,1,0.0,0,0.0,0,0,0.0,0,RJ,0,0,0,0.0,C,9,0,0
4,0,0.0,D,0.0,28,1,0.0,C,A,0.0,E,M,1,1,A,0,0.0,2,A,0.0,0,0,1,0.0,0,0.0,0,0,0.0,0,AM,0,0,0,0.0,B,4,0,0

## Selecionando columnas categorias apartir do dicionario

In [75]:
columns_categorical = df_train.select_dtypes(['object']).columns.to_list()

In [76]:
df_train[list(set(df_train.columns) - set(columns_categorical))]

,IN_SABATISTA,NU_NOTA_COMP3,TP_STATUS_REDACAO,NU_IDADE,TP_NACIONALIDADE,NU_NOTA_LC,NU_NOTA_COMP2,TP_LINGUA,TP_ESCOLA,IN_CEGUEIRA,NU_NOTA_CN,TP_COR_RACA,NU_NOTA_COMP4,IN_IDOSO,TP_PRESENCA_LC,TP_ST_CONCLUSAO,NU_NOTA_REDACAO,TP_PRESENCA_MT,NU_NOTA_CH,IN_BAIXA_VISAO,IN_DISCALCULIA,NU_NOTA_COMP1,IN_SURDEZ,TP_PRESENCA_CN,TP_PRESENCA_CH,IN_DISLEXIA,NU_NOTA_COMP5,IN_TREINEIRO,TP_ANO_CONCLUIU,IN_GESTANTE
0,0,120.0,1.0,24,1,581.2,120.0,1,1,0,436.3,1,80.0,0,1,1,520.0,1,495.4,0,0,120.0,0,1,1,0,80.0,0,4,0
1,0,120.0,1.0,17,1,599.0,120.0,1,2,0,474.5,3,120.0,0,1,2,580.0,1,544.1,0,0,140.0,0,1,1,0,80.0,0,0,0
2,0,0.0,0.0,21,1,0.0,0.0,1,1,0,0.0,3,0.0,0,0,3,0.0,0,0.0,0,0,0.0,0,0,0,0,0.0,0,0,0
3,0,0.0,0.0,25,1,0.0,0.0,0,1,0,0.0,0,0.0,0,0,1,0.0,0,0.0,0,0,0.0,0,0,0,0,0.0,0,9,0
4,0,0.0,0.0,28,1,0.0,0.0,1,1,0,0.0,2,0.0,0,0,1,0.0,0,0.0,0,0,0.0,0,0,0,0,0.0,0,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13725,0,80.0,1.0,20,1,394.5,120.0,0,1,0,438.2,1,80.0,0,1,1,440.0,1,419.7,0,0,120.0,0,1,1,0,40.0,0,3,0
13726,0,120.0,1.0,33,2,533.0,120.0,1,1,0,423.8,3,120.0,0,1,1,560.0,1,557.9,0,0,120.0,0,1,1,0,80.0,0,10,0
13727,0,120.0,1.0,15,1,569.3,120.0,0,1,0,460.5,1,120.0,0,1,3,600.0,1,528.9,0,0,120.0,0,1,1,0,120.0,1,0,0
13728,0,80.0,1.0,36,1,569.0,100.0,1,1,0,422.5,3,80.0,0,1,4,460.0,1,621.7,0,0,100.0,0,1,1,0,100.0,0,0,0
13729,0,80.0,1.0,17,1,565.9,120.0,0,2,0,488.7,1,120.0,0,1,2,520.0,1,575.3,0,0,120.0,0,1,1,0,80.0,0,0,0

In [77]:
columns_categorical = columns_categorical + ['TP_ST_CONCLUSAO']

In [78]:
df_train[columns_categorical].head()

  Q002 Q006 Q024 Q001 TP_SEXO Q047 Q025 SG_UF_RESIDENCIA Q026  TP_ST_CONCLUSAO
0    D    C    A    D       M    A    A               RS    C                1
1    A    B    A    A       F    A    A               CE    A                2
2    D    C    A    D       F    A    A               CE    A                3
3    E    E    C    H       F    D    B               RJ    C                1
4    D    C    A    E       M    A    A               AM    B                1

In [79]:
print('{} Colunas categoricas'.format(len(columns_categorical)))

10 Colunas categoricas

###  Dummy

### Train

In [80]:
df_train_dummy = pd.get_dummies(df_train, columns=columns_categorical)
df_train_dummy.head()

,IN_SABATISTA,NU_NOTA_COMP3,TP_STATUS_REDACAO,NU_IDADE,TP_NACIONALIDADE,NU_NOTA_LC,NU_NOTA_COMP2,TP_LINGUA,TP_ESCOLA,IN_CEGUEIRA,NU_NOTA_CN,TP_COR_RACA,NU_NOTA_COMP4,IN_IDOSO,TP_PRESENCA_LC,NU_NOTA_REDACAO,TP_PRESENCA_MT,NU_NOTA_CH,IN_BAIXA_VISAO,IN_DISCALCULIA,NU_NOTA_COMP1,IN_SURDEZ,IN_DISLEXIA,TP_PRESENCA_CN,TP_PRESENCA_CH,NU_NOTA_COMP5,TP_ANO_CONCLUIU,IN_GESTANTE,IN_TREINEIRO,Q002_A,Q002_B,Q002_C,Q002_D,Q002_E,Q002_F,Q002_G,Q002_H,Q006_A,Q006_B,Q006_C,Q006_D,Q006_E,Q006_F,Q006_G,Q006_H,Q006_I,Q006_J,Q006_K,Q006_L,Q006_M,Q006_N,Q006_O,Q006_P,Q006_Q,Q024_A,Q024_B,Q024_C,Q024_D,Q024_E,Q001_A,Q001_B,Q001_C,Q001_D,Q001_E,Q001_F,Q001_G,Q001_H,TP_SEXO_F,TP_SEXO_M,Q047_A,Q047_B,Q047_C,Q047_D,Q047_E,Q025_A,Q025_B,SG_UF_RESIDENCIA_AC,SG_UF_RESIDENCIA_AL,SG_UF_RESIDENCIA_AM,SG_UF_RESIDENCIA_AP,SG_UF_RESIDENCIA_BA,SG_UF_RESIDENCIA_CE,SG_UF_RESIDENCIA_DF,SG_UF_RESIDENCIA_ES,SG_UF_RESIDENCIA_GO,SG_UF_RESIDENCIA_MA,SG_UF_RESIDENCIA_MG,SG_UF_RESIDENCIA_MS,SG_UF_RESIDENCIA_MT,SG_UF_RESIDENCIA_PA,SG_UF_RESIDENCIA_PB,SG_UF_RESIDENCIA_PE,SG_UF_RESIDENCIA_PI,SG_UF_RESIDENCIA_PR,SG_UF_RESIDENCIA_RJ,SG_UF_RESIDENCIA_RN,SG_UF_RESIDENCIA_RO,SG_UF_RESIDENCIA_RR,SG_UF_RESIDENCIA_RS,SG_UF_RESIDENCIA_SC,SG_UF_RESIDENCIA_SE,SG_UF_RESIDENCIA_SP,SG_UF_RESIDENCIA_TO,Q026_A,Q026_B,Q026_C,TP_ST_CONCLUSAO_1,TP_ST_CONCLUSAO_2,TP_ST_CONCLUSAO_3,TP_ST_CONCLUSAO_4
0,0,120.0,1.0,24,1,581.2,120.0,1,1,0,436.3,1,80.0,0,1,520.0,1,495.4,0,0,120.0,0,0,1,1,80.0,4,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0
1,0,120.0,1.0,17,1,599.0,120.0,1,2,0,474.5,3,120.0,0,1,580.0,1,544.1,0,0,140.0,0,0,1,1,80.0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
2,0,0.0,0.0,21,1,0.0,0.0,1,1,0,0.0,3,0.0,0,0,0.0,0,0.0,0,0,0.0,0,0,0,0,0.0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
3,0,0.0,0.0,25,1,0.0,0.0,0,1,0,0.0,0,0.0,0,0,0.0,0,0.0,0,0,0.0,0,0,0,0,0.0,9,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0
4,0,0.0,0.0,28,1,0.0,0.0,1,1,0,0.0,2,0.0,0,0,0.0,0,0.0,0,0,0.0,0,0,0,0,0.0,4,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0

### Test

In [81]:
df_test = pd.read_csv('data/processed/test.csv')
df_test.head()

,IN_SABATISTA,NU_NOTA_COMP3,Q002,TP_STATUS_REDACAO,NU_IDADE,TP_NACIONALIDADE,NU_NOTA_LC,Q006,Q024,NU_NOTA_COMP2,Q001,TP_SEXO,TP_LINGUA,TP_ESCOLA,Q047,IN_CEGUEIRA,NU_NOTA_CN,TP_COR_RACA,Q025,NU_NOTA_COMP4,IN_IDOSO,TP_PRESENCA_LC,TP_ST_CONCLUSAO,NU_NOTA_REDACAO,TP_PRESENCA_MT,NU_NOTA_CH,IN_BAIXA_VISAO,IN_DISCALCULIA,NU_NOTA_COMP1,IN_SURDEZ,SG_UF_RESIDENCIA,IN_DISLEXIA,TP_PRESENCA_CN,TP_PRESENCA_CH,NU_NOTA_COMP5,Q026,TP_ANO_CONCLUIU,IN_GESTANTE,NU_INSCRICAO
0,0,0.0,E,0.0,19,1,0.0,H,B,0.0,E,F,1,1,A,0,495.3,1,B,0.0,0,0,1,0.0,0,593.3,0,0,0.0,0,RS,0,1,1,0.0,C,3,0,ba0cc30ba34e7a46764c09dfc38ed83d15828897
1,0,0.0,C,0.0,24,2,0.0,B,A,0.0,B,M,1,1,A,0,0.0,3,A,0.0,0,0,1,0.0,0,0.0,0,0,0.0,0,PA,0,0,0,0.0,C,4,0,177f281c68fa032aedbd842a745da68490926cd2
2,0,0.0,F,0.0,16,1,0.0,G,B,0.0,E,F,0,1,D,0,559.1,2,B,0.0,0,0,3,0.0,0,529.3,0,0,0.0,0,BA,0,1,1,0.0,A,0,0,6cf0d8b97597d7625cdedc7bdb6c0f052286c334
3,0,80.0,E,1.0,17,1,542.0,E,C,120.0,E,F,1,2,A,0,475.0,1,B,120.0,0,1,2,480.0,1,557.8,0,0,120.0,0,PR,0,1,1,40.0,B,0,0,5c356d810fa57671402502cd0933e5601a2ebf1e
4,0,160.0,E,1.0,19,1,594.2,E,B,160.0,E,F,1,1,A,0,440.5,1,B,160.0,0,1,1,720.0,1,596.1,0,0,160.0,0,DF,0,1,1,80.0,B,1,0,df47c07bd881c2db3f38c6048bf77c132ad0ceb3

In [82]:
df_test_dummy = pd.get_dummies(df_test, columns=columns_categorical)
df_test_dummy.head()

,IN_SABATISTA,NU_NOTA_COMP3,TP_STATUS_REDACAO,NU_IDADE,TP_NACIONALIDADE,NU_NOTA_LC,NU_NOTA_COMP2,TP_LINGUA,TP_ESCOLA,IN_CEGUEIRA,NU_NOTA_CN,TP_COR_RACA,NU_NOTA_COMP4,IN_IDOSO,TP_PRESENCA_LC,NU_NOTA_REDACAO,TP_PRESENCA_MT,NU_NOTA_CH,IN_BAIXA_VISAO,IN_DISCALCULIA,NU_NOTA_COMP1,IN_SURDEZ,IN_DISLEXIA,TP_PRESENCA_CN,TP_PRESENCA_CH,NU_NOTA_COMP5,TP_ANO_CONCLUIU,IN_GESTANTE,NU_INSCRICAO,Q002_A,Q002_B,Q002_C,Q002_D,Q002_E,Q002_F,Q002_G,Q002_H,Q006_A,Q006_B,Q006_C,Q006_D,Q006_E,Q006_F,Q006_G,Q006_H,Q006_I,Q006_J,Q006_K,Q006_L,Q006_M,Q006_N,Q006_O,Q006_P,Q006_Q,Q024_A,Q024_B,Q024_C,Q024_D,Q024_E,Q001_A,Q001_B,Q001_C,Q001_D,Q001_E,Q001_F,Q001_G,Q001_H,TP_SEXO_F,TP_SEXO_M,Q047_A,Q047_B,Q047_C,Q047_D,Q047_E,Q025_A,Q025_B,SG_UF_RESIDENCIA_AC,SG_UF_RESIDENCIA_AL,SG_UF_RESIDENCIA_AM,SG_UF_RESIDENCIA_AP,SG_UF_RESIDENCIA_BA,SG_UF_RESIDENCIA_CE,SG_UF_RESIDENCIA_DF,SG_UF_RESIDENCIA_ES,SG_UF_RESIDENCIA_GO,SG_UF_RESIDENCIA_MA,SG_UF_RESIDENCIA_MG,SG_UF_RESIDENCIA_MS,SG_UF_RESIDENCIA_MT,SG_UF_RESIDENCIA_PA,SG_UF_RESIDENCIA_PB,SG_UF_RESIDENCIA_PE,SG_UF_RESIDENCIA_PI,SG_UF_RESIDENCIA_PR,SG_UF_RESIDENCIA_RJ,SG_UF_RESIDENCIA_RN,SG_UF_RESIDENCIA_RO,SG_UF_RESIDENCIA_RR,SG_UF_RESIDENCIA_RS,SG_UF_RESIDENCIA_SC,SG_UF_RESIDENCIA_SE,SG_UF_RESIDENCIA_SP,SG_UF_RESIDENCIA_TO,Q026_A,Q026_B,Q026_C,TP_ST_CONCLUSAO_1,TP_ST_CONCLUSAO_2,TP_ST_CONCLUSAO_3,TP_ST_CONCLUSAO_4
0,0,0.0,0.0,19,1,0.0,0.0,1,1,0,495.3,1,0.0,0,0,0.0,0,593.3,0,0,0.0,0,0,1,1,0.0,3,0,ba0cc30ba34e7a46764c09dfc38ed83d15828897,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0
1,0,0.0,0.0,24,2,0.0,0.0,1,1,0,0.0,3,0.0,0,0,0.0,0,0.0,0,0,0.0,0,0,0,0,0.0,4,0,177f281c68fa032aedbd842a745da68490926cd2,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0
2,0,0.0,0.0,16,1,0.0,0.0,0,1,0,559.1,2,0.0,0,0,0.0,0,529.3,0,0,0.0,0,0,1,1,0.0,0,0,6cf0d8b97597d7625cdedc7bdb6c0f052286c334,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
3,0,80.0,1.0,17,1,542.0,120.0,1,2,0,475.0,1,120.0,0,1,480.0,1,557.8,0,0,120.0,0,0,1,1,40.0,0,0,5c356d810fa57671402502cd0933e5601a2ebf1e,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0
4,0,160.0,1.0,19,1,594.2,160.0,1,1,0,440.5,1,160.0,0,1,720.0,1,596.1,0,0,160.0,0,0,1,1,80.0,1,0,df47c07bd881c2db3f38c6048bf77c132ad0ceb3,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0

# Treinar e Validar

## Split

In [83]:
from sklearn.model_selection import train_test_split

In [84]:
columns_X = df_train_dummy.columns.to_list()
columns_X.remove('IN_TREINEIRO')
X = df_train_dummy[columns_X]
y = df_train_dummy[['IN_TREINEIRO']]

In [85]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## Treino

In [91]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

In [88]:
def validar(models, X_train, X_test, y_train, y_test):
    for model in models:
        models[model].fit(X_train, y_train)
    predicoes = {}
    for model in models:
        predicoes[model] = round(models[model].score(X_test, y_test), 4)
    return predicoes, models

In [92]:
models = {
    'KNC':KNeighborsClassifier(),
    'SVC':SVC(),
    'GPC':GaussianProcessClassifier(),
    'DTC':DecisionTreeClassifier(),
    'RFC':RandomForestClassifier(),
    'MLPC':MLPClassifier(),
    'ABC':AdaBoostClassifier(),
    'GNB':GaussianNB(),
    'QDA':QuadraticDiscriminantAnalysis()
}

In [93]:
predicoes = validar(models, X_train, X_test, y_train, y_test)

C:\Users\Helio Junior\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Helio Junior\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Helio Junior\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Helio Junior\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Helio Junior\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Helio Junior\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Helio Junior\anaconda3\lib\site-packages\sklearn\naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Helio Junior\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Helio Junior\anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:691: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

In [94]:
pd.Series(predicoes[0]).sort_values(ascending=False)

ABC     0.9967
RFC     0.9964
DTC     0.9953
MLPC    0.9858
GNB     0.9723
QDA     0.9650
SVC     0.8773
KNC     0.8762
GPC     0.8423
dtype: float64

In [108]:
predicoes[1]['RFC'].score(X_test, y_test)

0.9996358339402768

## Test

In [109]:
ajustes = list(set(columns_X) - set(df_test_dummy.columns))

In [110]:
ajustes

[]

In [111]:
for c in ajustes:
    df_test_dummy[c] = 0

In [112]:
X_val = df_test_dummy[columns_X]

In [113]:
resul = df_test_dummy[['NU_INSCRICAO']]

In [114]:
X_val_pca = pca.transform(X_val)

In [55]:
resul['IN_TREINEIRO'] = predicoes[1]['RFC'].predict(X_val_pca)

C:\Users\Helio Junior\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [57]:
resul.to_csv('answer.csv', index=False)